# Generated by Django 5.2.17 on 2026-10-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportMarker',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
